#lang racket
; The Box
(define (make-bob-box x y w h)
  (cons (cons x y) (cons w h)))
(define (bob-width box)
  (car (cdr box)))
(define (bob-height box)
  (cdr (cdr box)))
(define (bob-area box)
  (* (bob-width box)
     (bob-height box)))
(define (make-alice-box x1 y1 x2 y2)
  (cons (cons x1 y1) (cons x2 y2)))
(define (alice-width box)
  (abs (- (car (cdr box))
          (car (car box)))))
(define (alice-height box)
  (abs (- (cdr (cdr box))
          (cdr (car box)))))
(define (alice-area box)
  (* (alice-width box)
     (alice-height box)))